version: '3'

services:
  postgres:
    container_name: postgres
    image: postgres:latest
    environment:
      - POSTGRES_DB=radar-solidario
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "15432:5432"
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - postgres-network
      
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:latest
    environment:
      - PGADMIN_DEFAULT_EMAIL=projetos.uniacademia@gmail.com
      - PGADMIN_DEFAULT_PASSWORD=root
    ports:
      - "16543:80"
    depends_on:
      - postgres
    networks:
      - postgres-network

networks: 
  postgres-network:
    driver: bridge

volumes:
  postgresql:
  postgresql_data: